### ISSUE TITLE
error running labeler

### ISSUE THREAD

**Issue by lbbrhzn** [crazy-max/ghaction-github-labeler#221]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/crazy-max/ghaction-github-labeler/blob/master/.github/SUPPORT.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

After updating labeler from v5.0.0 to v5.1.0, there is an error running this action.

### Expected behaviour

No error

### Actual behaviour

2024-10-31T08:19:41.0817064Z 🏃 Running GitHub Labeler
2024-10-31T08:19:41.0851553Z ##[error]e.replace is not a function

### Steps to reproduce

update labeler version to v5.1.0 in workflow

### Repository URL

https://github.com/lbbrhzn/ocpp

### Workflow run URL

https://github.com/lbbrhzn/ocpp/actions/runs/11608401632

### YAML workflow

```yaml
name: Manage labels

on:
  push:
    branches:
      - main
      - master

jobs:
  labeler:
    name: Labeler
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Run Labeler
        uses: crazy-max/ghaction-github-labeler@v5.1.0
        with:
          skip-delete: true
```

### Workflow logs

2024-10-31T08:19:39.1239488Z Current runner version: '2.320.0'
2024-10-31T08:19:39.1262187Z ##[group]Operating System
2024-10-31T08:19:39.1262959Z Ubuntu
2024-10-31T08:19:39.1263314Z 22.04.5
2024-10-31T08:19:39.1263602Z LTS
2024-10-31T08:19:39.1264015Z ##[endgroup]
2024-10-31T08:19:39.1264407Z ##[group]Runner Image
2024-10-31T08:19:39.1264790Z Image: ubuntu-22.04
2024-10-31T08:19:39.1265264Z Version: 20241015.1.0
2024-10-31T08:19:39.1266241Z Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20241015.1/images/ubuntu/Ubuntu2204-Readme.md
2024-10-31T08:19:39.1267614Z Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20241015.1
2024-10-31T08:19:39.1268557Z ##[endgroup]
2024-10-31T08:19:39.1268975Z ##[group]Runner Image Provisioner
2024-10-31T08:19:39.1269412Z 2.0.384.1
2024-10-31T08:19:39.1269837Z ##[endgroup]
2024-10-31T08:19:39.1285925Z ##[group]GITHUB_TOKEN Permissions
2024-10-31T08:19:39.1287592Z Actions: write
2024-10-31T08:19:39.1288320Z Attestations: write
2024-10-31T08:19:39.1288779Z Checks: write
2024-10-31T08:19:39.1289227Z Contents: write
2024-10-31T08:19:39.1289626Z Deployments: write
2024-10-31T08:19:39.1290001Z Discussions: write
2024-10-31T08:19:39.1290461Z Issues: write
2024-10-31T08:19:39.1290788Z Metadata: read
2024-10-31T08:19:39.1291160Z Packages: write
2024-10-31T08:19:39.1291619Z Pages: write
2024-10-31T08:19:39.1291948Z PullRequests: write
2024-10-31T08:19:39.1292361Z RepositoryProjects: write
2024-10-31T08:19:39.1292905Z SecurityEvents: write
2024-10-31T08:19:39.1293287Z Statuses: write
2024-10-31T08:19:39.1293667Z ##[endgroup]
2024-10-31T08:19:39.1296789Z Secret source: Actions
2024-10-31T08:19:39.1297326Z Prepare workflow directory
2024-10-31T08:19:39.1912493Z Prepare all required actions
2024-10-31T08:19:39.2070949Z Getting action download info
2024-10-31T08:19:39.4133489Z Download action repository 'actions/checkout@v4' (SHA:11bd71901bbe5b1630ceea73d27597364c9af683)
2024-10-31T08:19:39.6764791Z Download action repository 'crazy-max/ghaction-github-labeler@v5.1.0' (SHA:b54af0c25861143e7c8813d7cbbf46d2c341680c)
2024-10-31T08:19:40.1761239Z Complete job name: Labeler
2024-10-31T08:19:40.2702555Z ##[group]Run actions/checkout@v4
2024-10-31T08:19:40.2703154Z with:
2024-10-31T08:19:40.2703606Z   repository: lbbrhzn/ocpp
2024-10-31T08:19:40.2704425Z   token: ***
2024-10-31T08:19:40.2704826Z   ssh-strict: true
2024-10-31T08:19:40.2705243Z   ssh-user: git
2024-10-31T08:19:40.2705749Z   persist-credentials: true
2024-10-31T08:19:40.2706211Z   clean: true
2024-10-31T08:19:40.2706628Z   sparse-checkout-cone-mode: true
2024-10-31T08:19:40.2707237Z   fetch-depth: 1
2024-10-31T08:19:40.2707623Z   fetch-tags: false
2024-10-31T08:19:40.2708047Z   show-progress: true
2024-10-31T08:19:40.2708543Z   lfs: false
2024-10-31T08:19:40.2708895Z   submodules: false
2024-10-31T08:19:40.2709327Z   set-safe-directory: true
2024-10-31T08:19:40.2709881Z ##[endgroup]
2024-10-31T08:19:40.4526471Z Syncing repository: lbbrhzn/ocpp
2024-10-31T08:19:40.4529354Z ##[group]Getting Git version info
2024-10-31T08:19:40.4530783Z Working directory is '/home/runner/work/ocpp/ocpp'
2024-10-31T08:19:40.4532749Z [command]/usr/bin/git version
2024-10-31T08:19:40.4533636Z git version 2.47.0
2024-10-31T08:19:40.4536924Z ##[endgroup]
2024-10-31T08:19:40.4552165Z Temporarily overriding HOME='/home/runner/work/_temp/7a9a662a-2918-4671-9c29-1c9419e706f3' before making global git config changes
2024-10-31T08:19:40.4554717Z Adding repository directory to the temporary git global config as a safe directory
2024-10-31T08:19:40.4556166Z [command]/usr/bin/git config --global --add safe.directory /home/runner/work/ocpp/ocpp
2024-10-31T08:19:40.4575285Z Deleting the contents of '/home/runner/work/ocpp/ocpp'
2024-10-31T08:19:40.4579171Z ##[group]Initializing the repository
2024-10-31T08:19:40.4584077Z [command]/usr/bin/git init /home/runner/work/ocpp/ocpp
2024-10-31T08:19:40.4643323Z hint: Using 'master' as the name for the initial branch. This default branch name
2024-10-31T08:19:40.4644908Z hint: is subject to change. To configure the initial branch name to use in all
2024-10-31T08:19:40.4647120Z hint: of your new repositories, which will suppress this warning, call:
2024-10-31T08:19:40.4648003Z hint:
2024-10-31T08:19:40.4649143Z hint: 	git config --global init.defaultBranch <name>
2024-10-31T08:19:40.4650366Z hint:
2024-10-31T08:19:40.4651741Z hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
2024-10-31T08:19:40.4653966Z hint: 'development'. The just-created branch can be renamed via this command:
2024-10-31T08:19:40.4655427Z hint:
2024-10-31T08:19:40.4656256Z hint: 	git branch -m <name>
2024-10-31T08:19:40.4657649Z Initialized empty Git repository in /home/runner/work/ocpp/ocpp/.git/
2024-10-31T08:19:40.4660855Z [command]/usr/bin/git remote add origin https://github.com/lbbrhzn/ocpp
2024-10-31T08:19:40.4695062Z ##[endgroup]
2024-10-31T08:19:40.4696545Z ##[group]Disabling automatic garbage collection
2024-10-31T08:19:40.4699962Z [command]/usr/bin/git config --local gc.auto 0
2024-10-31T08:19:40.4733194Z ##[endgroup]
2024-10-31T08:19:40.4734476Z ##[group]Setting up auth
2024-10-31T08:19:40.4739048Z [command]/usr/bin/git config --local --name-only --get-regexp core\.sshCommand
2024-10-31T08:19:40.4771819Z [command]/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :"
2024-10-31T08:19:40.5055941Z [command]/usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
2024-10-31T08:19:40.5085379Z [command]/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :"
2024-10-31T08:19:40.5321247Z [command]/usr/bin/git config --local http.https://github.com/.extraheader AUTHORIZATION: basic ***
2024-10-31T08:19:40.5364943Z ##[endgroup]
2024-10-31T08:19:40.5366520Z ##[group]Fetching the repository
2024-10-31T08:19:40.5375536Z [command]/usr/bin/git -c protocol.version=2 fetch --no-tags --prune --no-recurse-submodules --depth=1 origin +2dd026ee4861b5aa2a2a96e3b4f005dbb3ea1d13:refs/remotes/origin/main
2024-10-31T08:19:40.7520531Z From https://github.com/lbbrhzn/ocpp
2024-10-31T08:19:40.7522083Z  * [new ref]         2dd026ee4861b5aa2a2a96e3b4f005dbb3ea1d13 -> origin/main
2024-10-31T08:19:40.7548284Z ##[endgroup]
2024-10-31T08:19:40.7549013Z ##[group]Determining the checkout info
2024-10-31T08:19:40.7550152Z ##[endgroup]
2024-10-31T08:19:40.7555526Z [command]/usr/bin/git sparse-checkout disable
2024-10-31T08:19:40.7596442Z [command]/usr/bin/git config --local --unset-all extensions.worktreeConfig
2024-10-31T08:19:40.7624375Z ##[group]Checking out the ref
2024-10-31T08:19:40.7629292Z [command]/usr/bin/git checkout --progress --force -B main refs/remotes/origin/main
2024-10-31T08:19:40.7750640Z Switched to a new branch 'main'
2024-10-31T08:19:40.7753528Z branch 'main' set up to track 'origin/main'.
2024-10-31T08:19:40.7759168Z ##[endgroup]
2024-10-31T08:19:40.7794794Z [command]/usr/bin/git log -1 --format=%H
2024-10-31T08:19:40.7819021Z 2dd026ee4861b5aa2a2a96e3b4f005dbb3ea1d13
2024-10-31T08:19:40.8109177Z ##[group]Run crazy-max/ghaction-github-labeler@v5.1.0
2024-10-31T08:19:40.8109716Z with:
2024-10-31T08:19:40.8110132Z   skip-delete: true
2024-10-31T08:19:40.8110458Z   yaml-file: .github/labels.yml
2024-10-31T08:19:40.8110861Z   dry-run: false
2024-10-31T08:19:40.8111446Z   github-token: ***
2024-10-31T08:19:40.8111751Z ##[endgroup]
2024-10-31T08:19:41.0737393Z 👉 Current labels
2024-10-31T08:19:41.0738910Z - name: breaking
2024-10-31T08:19:41.0740022Z   color: bfd4f2
2024-10-31T08:19:41.0740919Z   description: Breaking Changes
2024-10-31T08:19:41.0743743Z - name: bug
2024-10-31T08:19:41.0744317Z   color: d73a4a
2024-10-31T08:19:41.0766321Z   description: Something isn't working
2024-10-31T08:19:41.0767427Z - name: build
2024-10-31T08:19:41.0767990Z   color: bfdadc
2024-10-31T08:19:41.0769613Z   description: Build System and Dependencies
2024-10-31T08:19:41.0771199Z - name: charger_bug
2024-10-31T08:19:41.0771678Z   color: 4A040D
2024-10-31T08:19:41.0772588Z   description: Upstream bug or configuration issue
2024-10-31T08:19:41.0773439Z - name: ci
2024-10-31T08:19:41.0773928Z   color: 4a97d6
2024-10-31T08:19:41.0774667Z   description: Continuous Integration
2024-10-31T08:19:41.0775481Z - name: dependencies
2024-10-31T08:19:41.0776033Z   color: 0366d6
2024-10-31T08:19:41.0777216Z   description: Pull requests that update a dependency file
2024-10-31T08:19:41.0778147Z - name: documentation
2024-10-31T08:19:41.0780673Z   color: 0075ca
2024-10-31T08:19:41.0781457Z   description: Improvements or additions to documentation
2024-10-31T08:19:41.0782398Z - name: Done
2024-10-31T08:19:41.0782954Z   color: 3C19F2
2024-10-31T08:19:41.0783521Z   description: Has been released to master
2024-10-31T08:19:41.0784423Z - name: duplicate
2024-10-31T08:19:41.0784886Z   color: cfd3d7
2024-10-31T08:19:41.0785527Z   description: This issue or pull request already exists
2024-10-31T08:19:41.0786508Z - name: enhancement
2024-10-31T08:19:41.0786988Z   color: a2eeef
2024-10-31T08:19:41.0787641Z   description: New feature or request
2024-10-31T08:19:41.0788600Z - name: github_actions
2024-10-31T08:19:41.0789261Z   color: '000000'
2024-10-31T08:19:41.0790076Z   description: Pull requests that update Github_actions code
2024-10-31T08:19:41.0791138Z - name: good first issue
2024-10-31T08:19:41.0791714Z   color: 7057ff
2024-10-31T08:19:41.0792372Z   description: Good for newcomers
2024-10-31T08:19:41.0792998Z - name: help wanted
2024-10-31T08:19:41.0793567Z   color: '008672'
2024-10-31T08:19:41.0794301Z   description: Extra attention is needed
2024-10-31T08:19:41.0795007Z - name: invalid
2024-10-31T08:19:41.0795522Z   color: e4e669
2024-10-31T08:19:41.0796298Z   description: This doesn't seem right
2024-10-31T08:19:41.0797015Z - name: no-issue-activity
2024-10-31T08:19:41.0797651Z   color: ededed
2024-10-31T08:19:41.0798200Z   description: ''
2024-10-31T08:19:41.0799032Z - name: no-pr-activity
2024-10-31T08:19:41.0799723Z   color: ededed
2024-10-31T08:19:41.0800322Z   description: ''
2024-10-31T08:19:41.0801050Z - name: performance
2024-10-31T08:19:41.0801738Z   color: '016175'
2024-10-31T08:19:41.0802326Z   description: Performance
2024-10-31T08:19:41.0802948Z - name: python
2024-10-31T08:19:41.0803524Z   color: 2b67c6
2024-10-31T08:19:41.0804185Z   description: Pull requests that update Python code
2024-10-31T08:19:41.0805130Z - name: question
2024-10-31T08:19:41.0805639Z   color: d876e3
2024-10-31T08:19:41.0806221Z   description: Further information is requested
2024-10-31T08:19:41.0807100Z - name: refactoring
2024-10-31T08:19:41.0807576Z   color: ef67c4
2024-10-31T08:19:41.0808099Z   description: Refactoring
2024-10-31T08:19:41.0808868Z - name: removal
2024-10-31T08:19:41.0809362Z   color: 9ae7ea
2024-10-31T08:19:41.0809981Z   description: Removals and Deprecations
2024-10-31T08:19:41.0810883Z - name: style
2024-10-31T08:19:41.0811524Z   color: c120e5
2024-10-31T08:19:41.0812015Z   description: Style
2024-10-31T08:19:41.0812721Z - name: testing
2024-10-31T08:19:41.0813167Z   color: b1fc6f
2024-10-31T08:19:41.0814171Z   description: Testing
2024-10-31T08:19:41.0814957Z - name: wontfix
2024-10-31T08:19:41.0815432Z   color: ffffff
2024-10-31T08:19:41.0816059Z   description: This will not be worked on
2024-10-31T08:19:41.0816543Z 
2024-10-31T08:19:41.0817064Z 🏃 Running GitHub Labeler
2024-10-31T08:19:41.0851553Z ##[error]e.replace is not a function
2024-10-31T08:19:41.1509136Z Post job cleanup.
2024-10-31T08:19:41.2516424Z [command]/usr/bin/git version
2024-10-31T08:19:41.2558306Z git version 2.47.0
2024-10-31T08:19:41.2608903Z Temporarily overriding HOME='/home/runner/work/_temp/2a0ebe7b-a541-49bb-b7bb-a21bfa28c373' before making global git config changes
2024-10-31T08:19:41.2610647Z Adding repository directory to the temporary git global config as a safe directory
2024-10-31T08:19:41.2612113Z [command]/usr/bin/git config --global --add safe.directory /home/runner/work/ocpp/ocpp
2024-10-31T08:19:41.2650230Z [command]/usr/bin/git config --local --name-only --get-regexp core\.sshCommand
2024-10-31T08:19:41.2683906Z [command]/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :"
2024-10-31T08:19:41.2926734Z [command]/usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
2024-10-31T08:19:41.2947623Z http.https://github.com/.extraheader
2024-10-31T08:19:41.2960029Z [command]/usr/bin/git config --local --unset-all http.https://github.com/.extraheader
2024-10-31T08:19:41.2993991Z [command]/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :"
2024-10-31T08:19:41.3432418Z Cleaning up orphan processes

**Comment by gaspardc-met** [comment]
Hello,

Any updates on this @crazy-max ?
I know it's probably a side project, but a broken latest release is a pain
(especially with tool like renovate that see the new release and creates a broken PR)

thanks

**Comment by crazy-max** [comment]
Seems related to this change https://github.com/crazy-max/ghaction-github-labeler/pull/207/files#diff-448984110104fc17eadbe4ddc66981a4282fbc78e1dd5e84daf782f4e266fe7cR341

@pjpires Can you take a look?

**Comment by crazy-max** [comment]
@pjpires Thanks for looking at it, I think option 2) is fine if we have enough tests to cover cases.
